apiVersion: v1
kind: Secret
metadata:
  name: hello-world-client-jwt
  labels:
    konghq.com/credential: jwt
type: Opaque
stringData:
  algorithm: RS256
  key: hello-world-client
  secret: dummy
  rsa_public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0Cbm20fESYjezjEtL58T
    Sp6S5bu81nDlYpk8w8JARi6nV+rqH2Rl4tVcz/xwZhqXngHYUWMIPFEE+TcfSNfj
    +XRbJkr55KrRcqFRXoPRc/oApEwkkWYPbMNJ5CEvxvHJk+Jgq81EGlNtbLq1mMwz
    CHAqVUMh8CUjmqZMxG32jkvshTHXHgk4VtWGC6ZzAbKbLALhs45Wjp0lg+FeYcmw
    YUK4oZmoyFrYuHf9HAKD3mAI+KfIINUS5tT5Co7I5vRCY0Ak7q/7z2106b6z7F2w
    OHwZAGlxqu+91CGTxziMRJ+srGCwu/4jN9BoX0/TqKLhcvY5wxgi+KSIDhKReqKJ
    NQIDAQAB
    -----END PUBLIC KEY-----
