apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route-kong.yaml

images:
  - name: APP_IMAGE
    newName: hello-world-api
    newTag: latest
